# COMMON
scoring: mse
image_size: 256
batch_size: 32
metrics: 
      - mae


# DATA INTO BATCHES SPLITTER
data_into_batches_splitter: 
      train_size: 0.8
      val_size: 0.1

# MODEL TRAINING
model_trainer: 
      is_first_time: t # t or f
      model_name: REGRESSOR_1
      epochs: 50
      callbacks: 
            - EarlyStopping(monitor='val_mse', patience=10, min_delta=100)
      model_training_type: o # o: one model, m: many models
      list_layers: 
            -
                  - Input(shape=(256; 256; 3))
                  - ManyConvNetBlocks_XceptionVersion(list_filters = [32; 64; 128; 256])
                  - Dense(3, activation = 'softmax')
            -
                  - Input(shape=(256; 256; 3))
                  - ManyConvNetBlocks_Advanced(list_filters = [32; 64; 128; 256])
                  - Dense(3, activation = 'softmax')
            -
                  - Input(shape=(256; 256; 3))
                  - Dense(3, activation = 'softmax')
            
      optimizer: RMSprop()
      loss: mse



# MODEL EVALUATION
model_evaluation: 
      model_name: CONVNET_30

# MONITOR PLOT
monitor_plotter:
      monitor_plot_html_path: "artifacts/model_trainer/monitor_plot.html"
      monitor_plot_fig_path: "artifacts/model_trainer/monitor_plot_fig.pkl"
      target_val_value: 99.9
      max_val_value: 100
      dtick_y_value: 5
