# COMMON
scoring: accuracy
image_size: 256
batch_size: 16
metrics: 
      - accuracy


# DATA INTO BATCHES SPLITTER
data_into_batches_splitter: 
      train_size: 0.8
      val_size: 0.1

# MODEL TRAINING
model_trainer: 
      is_first_time: f # t or f
      model_name: CONVNET_13
      epochs: 50
      callbacks: 
            - EarlyStopping(monitor='accuracy', patience=1, min_delta=1)
      model_training_type: m # o: one model, m: many models
      list_layers: 
            -
                  - Input(shape=(256; 256; 3))
                  - Flatten()
                  - Dense(units = 64, activation = 'softmax')
                  - Dense(units = 3, activation = 'softmax')
            -
                  - Input(shape=(256; 256; 3))
                  - Flatten()
                  - Dense(units = 128, activation = 'softmax')
                  - Dense(units = 3, activation = 'softmax')
            
      optimizer: RMSprop()
      loss: sparse_categorical_crossentropy



# MODEL EVALUATION
model_evaluation: 
      model_name: CONVNET_30

# MONITOR PLOT
monitor_plotter:
      monitor_plot_html_path: "artifacts/model_trainer/monitor_plot.html"
      monitor_plot_fig_path: "artifacts/model_trainer/monitor_plot_fig.pkl"
      target_val_value: 99.9
      max_val_value: 100
      dtick_y_value: 5
