# COMMON
scoring: accuracy
image_size: 256
batch_size: 16
metrics: 
      - accuracy


# DATA INTO BATCHES SPLITTER
data_into_batches_splitter: 
      train_size: 0.8
      val_size: 0.1

# MODEL TRAINING
model_trainer: 
      model_name: CONVNET_28
      epochs: 50
      callbacks: 
            - EarlyStopping(monitor='val_accuracy', patience=5, min_delta=0.01)
      list_layers: 
            -
                  - Input(shape=(256; 256; 3))
                  - ConvNetBlock_Advanced(filters = 32)
                  - ConvNetBlock_Advanced(filters = 64)
                  - ConvNetBlock_Advanced(filters = 128)
                  - Flatten()
                  - Dense(units = 64, activation = 'relu')
                  - Dense(units = 32, activation = 'relu')
                  - Dense(units = 3, activation = 'softmax')
            
      optimizer: RMSprop()
      loss: sparse_categorical_crossentropy



# MODEL EVALUATION
model_evaluation: 
      model_name: CONVNET_30

# MONITOR PLOT
monitor_plotter:
      monitor_plot_html_path: "artifacts/model_trainer/monitor_plot.html"
      monitor_plot_fig_path: "artifacts/model_trainer/monitor_plot_fig.pkl"
      target_val_value: 99.9
      max_val_value: 100
      dtick_y_value: 5
