# COMMON
scoring: accuracy
image_size: 256
batch_size: 32

# MODEL TRAINING
model_trainer: 
      is_first_time: f # t or f
      model_name: CONVNET_36
      epochs: 50
      callbacks: 
            - EarlyStopping(monitor='val_accuracy', patience=1, min_delta=1)
      layers: 
            # data augmentation 
            - ImageDataPositionAugmentation()
            - ImageDataColorAugmentation()

            # rescale 
            - Rescaling(scale = 0.00392) # 1 / 255

            # pretrained model 
            # - PretrainedModel(name='vgg16')

            # Convnet 
            - ConvNetBlock(filters = 32)
            - ConvNetBlock_Advanced(filters = 64)
            - ConvNetBlock_XceptionVersion(filters = 128, name='last_convnet')

            # Classifier
            - Flatten()
            - Dense(units=  64, activation='relu')

      optimizer: RMSprop()
      loss: sparse_categorical_crossentropy
      metrics: 
            - accuracy


# MODEL EVALUATION
evaluated_model_name: XGB_1

# MONITOR PLOT
monitor_plotter:
      monitor_plot_html_path: "artifacts/model_trainer/monitor_plot.html"
      monitor_plot_fig_path: "artifacts/model_trainer/monitor_plot_fig.pkl"
      target_val_value: 99.9
      max_val_value: 100
      dtick_y_value: 5
