# COMMON
scoring: accuracy
image_size: 256
batch_size: 32

# MODEL TRAINING
model_trainer: 
      is_first_time: f # t or f
      model_name: CONVNET_19
      epochs: 50
      callbacks: 
            - EarlyStopping(monitor='val_accuracy', patience=3, min_delta=0.01)
      layers: 
            # data augmentation 
            - RandomFlip(mode='horizontal_and_vertical')
            - RandomRotation(factor=0.2)
            - RandomZoom(height_factor=0.2)
            # - RandomBrightness(factor=0.2)
            # - RandomGaussianBlur(kernel_size=3, factor=(0.0, 1.0))
            # - RandomContrast(factor=0.2)
            # - RandomHue(factor=0.08) 
            # - RandomSaturation(factor=0.3)

            # rescale 
            - Rescaling(scale = 0.00392) # 1 / 255

            # Convnet 
            - Conv2D(filters=32, kernel_size=3, activation='relu')
            - MaxPooling2D(pool_size=2)

            - Conv2D(filters=64, kernel_size=3, activation='relu')
            - MaxPooling2D(pool_size=2)

            - Conv2D(filters=128, kernel_size=3, activation='relu')
            - Conv2D(filters=128, kernel_size=3, activation='relu')
            - MaxPooling2D(pool_size=2)

            - Conv2D(filters=256, kernel_size=3, activation='relu')
            - Conv2D(filters=256, kernel_size=3, activation='relu')
            - MaxPooling2D(pool_size=2)

            - Conv2D(filters=256, kernel_size=3, activation='relu')
            

            # Classifier
            - Flatten()
            - Dense(units=  64, activation='relu')
            - Dense(units=  32, activation='relu')

      optimizer: RMSprop()
      loss: sparse_categorical_crossentropy
      metrics: 
            - accuracy


# MODEL EVALUATION
evaluated_model_name: XGB_1

# MONITOR PLOT
monitor_plotter:
      monitor_plot_html_path: "artifacts/model_trainer/monitor_plot.html"
      monitor_plot_fig_path: "artifacts/model_trainer/monitor_plot_fig.pkl"
      target_val_value: 99.9
      max_val_value: 100
      dtick_y_value: 5
